apiVersion: v1
kind: Service
metadata:
  labels:
    app: kl-svc
  name: kl-svc
  namespace: sandesh-dulal
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: 8080-80
      nodePort: 32124
      port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: kl-todo
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
