name: Deploy to Kubernetes

on:
  push:
    branches:
      - bearbeitung # Set this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.20.0' # Set this to the version of kubectl you want to use

      - name: Configure Kubernetes Cluster
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Create namespace
        run: kubectl create namespace sandesh-dulal --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment/deployment.yaml
          kubectl apply -f deployment/service.yaml

      - name: Set imagePullSecret
        uses: azure/k8s-create-secret@v4
        with:
          namespace: 'sandesh.dulal'
          secret-name: 'regcred'
          container-registry-url: 'ghcr'
          container-registry-username: ${{ github.actor }}
          container-registry-password: ${{ secrets.GITHUB_TOKEN }}
        id: create-secret
